## Class - 2/25/20

## ISLR Chapter 2

### 2.1.1


* **What is f?** 

F is a function a relationship between our x's and y

* **Why do we care about estimating f?** 

Because F is unknown

* **Describe the two types of errors in a model.** 

Reducable and Irreducable error reducible we can eliminate Irreducable we cannot
f(x) is a Reducable error and epsilon is our irreducable

$$y = f(x) + \epsilon $$
* **What concept in 456 does irreducible error portion of the model correspond to?** 

### 2.2.1

* **What is the primary measure of model accuracy for regression model**
Reducable and Irreducable error

* **Compare and contrast the smoothing spline to a linear regression line (what is the same and what is different)**

### 2.2.2

* **What is the difference between training and testing data. Why do we need both**

* **What is overfitting**

It is when are model begins to describe randomization of data.  You can tell by low MSE on training but high MSE on testing.

* **If we don't have a testing data set, what methos can we use to estimate the MSE of the testing data?**

We can show the expected test MSE as the sum of the variance of $var(\hat{f})$ the square bias of and $var(\epsilon)$ 

Bias is (obs $\bar{x}$ - true $\mu$)

$\mu$ is predicted 

### 2.2.3

* **What is the bias variance trade off**

As bias decreases variance increases

* **What is the primary measure of model accuracy for classification**

Training error rate 
Porportion of mistakes made on training observations

there is no mse classification cause you either right or wrong

Testing error rate

* **What is the Bayes Classifier**

Bayes theorm $P(A|B)=\frac{P(B|A)P(A)}{P(B)}$

* **Bayes Error Rate**

Used to reduce test error rate.  It is limiting in that you need more data about the topic outside the subject.


### 2.2.3

* **Describe how KNN classfier work**
  Find the distance between a query selecting the k-numbers of neighbors the judges or averages

* **Name a benefit of using KNN model** 
  

* **What happens to the accuracy/bias of the model as the K increases. Why?**


Chapter 3 is it a good research question.

* What is the mathmatical model
* What are the data types
* What is the approriate visualization